### PR TITLE
Support custom chains and default policies

### LINKED ISSUE #11: new chains?
should this cookbook allow for new chains to be created or should we always use the standard ones?

I like to be able to use different chains for organizational purposes. Thoughts?

### PR DESCRIPTION
**Pull request by bison**
This adds support for defining custom chains in each table, and setting default policies on the built-in chains. It's a little rough around the edges, but I wanted to get it out there to see if there's any interest in going this route.

This changes the interface, so it would probably require a bump to v2.0. Though, with some extra work, we might be able make it backwards compatible by merging the old hashes into the new and doing some guessing in the helper functions...

Examples:

``` ruby
node.default['rackspace_iptables']['v4']['filter']['INPUT']['default'] = 'DROP [0:0]'
node.default['rackspace_iptables']['v4']['filter']['INPUT']['-s 10.0.0.1/32 -j ACCEPT'] = {
  weight: 1,
  comment: 'foo'
}

add_iptables_rule 'filter', 'INPUT', '-s 10.0.0.6 -j ACCEPT', 70, 'foo2'
```

Fixes #11.

### CODE REVIEW

**Comment by martinb3** [comment]
@bison thanks for the contribution! We've actually been moving away from this towards using upstream. I think we only have legacy customers using it these days.

This PR also appears to be failing some lint checks:

``````
Running RuboCop...
Inspecting 8 files
.C......

Offenses:

libraries/helpers.rb:24:3: C: Missing top-level module documentation comment.
  module TemplateHelpers
  ^^^^^^
libraries/helpers.rb:86:34: C: Avoid parameter lists longer than 5 parameters.
    def search_add_iptables_rules(search_str, table, chain, rules_to_add, weight = DEFAULT_WEIGHT, comment = search_str) # ```
``````

**Comment by bison** [comment]
Thanks, @martinb3. I thought that might be the case.

When you say upstream, do you mean the opscode iptables cookbook, iptables-ng, or something else?

**Comment by martinb3** [comment]
Hi @bison -- we'd like to end up on the firewall cookbook (new implementations start there now), but even for older implementations, we've moved to the upstream iptables instead of rackspace_iptables.

**Comment by bison** [comment]
Ah, makes sense. I'm coming back to Chef after some time with Ansible, and I haven't looked at that lately.

I'll close this and experiment there. Thanks!

**Pull request closed without merging**
